version: '2'
services: 
  golang:
    build: .
    container_name: "dc_go"
    ports: 
     - "8080:8080"
    network_mode: "test-net"
    depends_on:
      - mysql
  mysql:
    image: "mysql"
    container_name: "dc_mydb"
    network_mode: "test-net"
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #你的root密码
      MYSQL_ROOT_HOST: "%"
    ports: 
     - "3306:3306"